### ISSUE TITLE
Can I use this dataset for my research?

### ISSUE THREAD

**Issue by y12uc231** [vaskonov/negochat_corpus#1]
Hi, 

Can I use this dataset for my research, I am a graduate student in CMU. Let me know if there is specific I need to mention in the citations.

**Comment by vaskonov** [comment]
Dear Satyapriya Krishna, 

Thank you very much for your interest. Of course you can use this corpus. I've updated the repository description. Do not hesitate to ask me any further question regarding this research. Please use the following BibTeX reference.

```
@inproceedings{konovalov2016negochat,
  title={The Negochat Corpus of Human-agent Negotiation Dialogues},
  author={Konovalov, Vasily and Artstein, Ron and Melamud, Oren and Dagan, Ido},
  booktitle={Proceedings of the 10th International Conference on Language Resources and Evaluation, LREC 2016},
  year={2016},
  pages={3141-3145},
  url={www.lrec-conf.org/proceedings/lrec2016/pdf/240_Paper.pdf}
}
```
